# Generated by Django 4.0 on 2024-12-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_details_kcno'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('doc_file', models.CharField(max_length=250)),
                ('dt', models.CharField(max_length=15)),
                ('tm', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='marklist_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_master_id', models.IntegerField()),
                ('sub1_id', models.IntegerField()),
                ('sub1_mark', models.FloatField()),
                ('sub2_id', models.IntegerField()),
                ('sub2_mark', models.FloatField()),
                ('sub3_id', models.IntegerField()),
                ('sub3_mark', models.FloatField()),
                ('sub4_id', models.IntegerField()),
                ('sub4_mark', models.FloatField()),
                ('sub5_id', models.IntegerField()),
                ('sub5_mark', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='module_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_details_id', models.IntegerField()),
                ('module_title', models.CharField(max_length=100)),
                ('module_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='question_bank1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('doc_id', models.IntegerField()),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=1000)),
                ('mark', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='schedule_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_master_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('priority', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='schedule_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('subjects', models.CharField(max_length=100)),
                ('total_duration', models.IntegerField()),
                ('dt', models.CharField(max_length=15)),
                ('tm', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='schedule_planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_master_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('module_id', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('dt', models.CharField(max_length=15)),
                ('tm', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='subject_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='age',
        ),
        migrations.AddField(
            model_name='user_details',
            name='dob',
            field=models.CharField(default=' ', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_details',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
