# Generated by Django 4.0 on 2024-12-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_doc_pool_marklist_details_module_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_bank2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('doc_id', models.IntegerField()),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=1000)),
                ('mark', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='question_bank3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('doc_id', models.IntegerField()),
                ('question', models.CharField(max_length=300)),
                ('op1', models.CharField(max_length=300)),
                ('op2', models.CharField(max_length=300)),
                ('op3', models.CharField(max_length=300)),
                ('op4', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300)),
                ('mark', models.FloatField()),
            ],
        ),
    ]
